import React, { useState, useEffect } from 'react';
import jsPDF from 'jspdf';
import {
  Download,
  ShieldCheck,
  RefreshCw
} from 'lucide-react';
import { Incident } from '../types/index.js';

interface ReportsViewProps {
  incidents: Incident[];
  selectedIncidentId: string | null;
  onSelectIncident: (incidentId: string) => void;
}

export const ReportsView: React.FC<ReportsViewProps> = ({
  incidents,
  selectedIncidentId,
  onSelectIncident
}) => {
  const [reportData, setReportData] = useState<any>(null);
  const [loading, setLoading] = useState(false);

  const activeIncidentId = selectedIncidentId || (incidents[0] ? incidents[0].incident_id : '');

  const fetchReport = async (incId: string) => {
    if (!incId) return;
    setLoading(true);
    try {
      const res = await fetch(`/api/reports/${incId}`);
      const data = await res.json();
      setReportData(data);
    } catch (err) {
      console.error('Failed to fetch report payload:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (activeIncidentId) {
      fetchReport(activeIncidentId);
    }
  }, [activeIncidentId]);

  const handleDownloadPdf = () => {
    if (!reportData) return;

    const doc = new jsPDF();
    const margin = 15;
    let y = 20;

    // Title
    doc.setFontSize(18);
    doc.setTextColor(15, 23, 42);
    doc.text('FlightRecorder AI — Incident Report', margin, y);
    y += 10;

    // Subtitle & Timestamp
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text(`Report ID: ${reportData.incident.incident_id}  |  Generated: ${new Date().toLocaleString()}`, margin, y);
    y += 10;

    // Divider Line
    doc.setDrawColor(203, 213, 225);
    doc.line(margin, y, 195, y);
    y += 10;

    // Section 1: Incident Summary
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    doc.text('1. Incident Summary', margin, y);
    y += 7;

    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85);
    doc.text(`Session ID: ${reportData.session?.session_id || 'N/A'}`, margin, y); y += 6;
    doc.text(`User Task: "${reportData.session?.user_prompt || 'N/A'}"`, margin, y); y += 6;
    doc.text(`Severity: ${reportData.incident.severity.toUpperCase()}  |  Status: ${reportData.incident.status.toUpperCase()}`, margin, y); y += 6;
    doc.text(`Reason: ${reportData.incident.reason}`, margin, y); y += 12;

    // Section 2: Root Cause Diagnosis
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    doc.text('2. Root Cause Analysis', margin, y);
    y += 7;

    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85);
    doc.text(`Step: Step ${reportData.root_cause_log?.step_number || 'N/A'} (${reportData.root_cause_log?.action || 'N/A'})`, margin, y); y += 6;
    doc.text(`Tool Used: ${reportData.root_cause_log?.tool_used || 'N/A'}`, margin, y); y += 6;
    doc.text(`Confidence: ${reportData.incident.confidence}%`, margin, y); y += 10;

    // Recommendation
    doc.setFontSize(11);
    doc.setTextColor(234, 88, 12);
    doc.text('Recommendation:', margin, y); y += 6;
    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85);
    const splitRec = doc.splitTextToSize(reportData.incident.recommendation, 175);
    doc.text(splitRec, margin, y);
    y += splitRec.length * 6 + 10;

    // Section 3: Hash Integrity Verification
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    doc.text('3. Security Hash Verification', margin, y);
    y += 7;

    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85);
    doc.text(`Hash Status: ${reportData.hash_integrity?.is_valid ? 'VERIFIED INTACT' : 'TAMPERING DETECTED'}`, margin, y); y += 6;
    doc.text(`Total Steps Executed: ${reportData.hash_integrity?.total_steps || 0}`, margin, y); y += 12;

    // Footer
    doc.setFontSize(9);
    doc.setTextColor(148, 163, 184);
    doc.text('Generated by FlightRecorder AI log monitoring system.', margin, 280);

    doc.save(`Incident_Report_${reportData.incident.incident_id}.pdf`);
  };

  return (
    <div className="space-y-6 font-sans">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-800 pb-4">
        <div>
          <h1 className="text-xl font-bold text-white">
            PDF Incident Reports
          </h1>
          <p className="text-xs text-slate-400">
            Export formal incident briefs with complete telemetry evidence and solutions
          </p>
        </div>

        <div className="flex items-center space-x-3">
          <label className="text-xs text-slate-400 font-semibold">Incident:</label>
          <select
            value={activeIncidentId}
            onChange={(e) => onSelectIncident(e.target.value)}
            className="px-3 py-1.5 rounded bg-slate-900 border border-slate-800 text-xs text-orange-400 font-bold focus:outline-none focus:border-orange-500"
          >
            {incidents.map((i) => (
              <option key={i._id} value={i.incident_id}>
                {i.incident_id} — {i.reason.slice(0, 30)}...
              </option>
            ))}
          </select>

          <button
            onClick={handleDownloadPdf}
            disabled={!reportData}
            className="px-4 py-1.5 rounded bg-orange-600 hover:bg-orange-500 text-white font-semibold text-xs flex items-center space-x-2 transition cursor-pointer"
          >
            <Download className="w-4 h-4" />
            <span>Download PDF</span>
          </button>
        </div>
      </div>

      {/* Report Preview */}
      {reportData ? (
        <div className="bg-slate-900/50 border border-slate-800 rounded-lg p-8 max-w-4xl mx-auto space-y-6 text-slate-200">
          {/* Header */}
          <div className="border-b border-slate-800 pb-5 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
            <div>
              <div className="flex items-center space-x-3 mb-1">
                <span className="px-2.5 py-0.5 rounded bg-orange-500/10 text-orange-400 border border-orange-500/20 text-xs font-bold">
                  {reportData.incident.incident_id}
                </span>
                <span className="text-lg font-bold text-white">
                  Incident Brief
                </span>
              </div>
              <p className="text-xs text-slate-400">
                Generated: {new Date(reportData.generated_at).toLocaleString()}
              </p>
            </div>

            <div className="flex items-center space-x-2">
              <span className="px-2.5 py-1 rounded bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 text-xs font-semibold flex items-center space-x-1.5">
                <ShieldCheck className="w-4 h-4 text-emerald-400" />
                <span>Verified Log Integrity</span>
              </span>
            </div>
          </div>

          {/* Executive Overview */}
          <div className="space-y-3">
            <h3 className="text-xs font-bold uppercase tracking-wider text-orange-400 border-b border-slate-800 pb-2">
              1. Overview
            </h3>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs bg-slate-950 p-4 rounded border border-slate-800">
              <div>
                <span className="text-slate-400 block font-semibold mb-0.5">Session ID:</span>
                <span className="text-orange-400 font-bold">{reportData.session?.session_id}</span>
              </div>

              <div>
                <span className="text-slate-400 block font-semibold mb-0.5">User Task:</span>
                <span className="text-slate-200">{reportData.session?.user_prompt}</span>
              </div>

              <div>
                <span className="text-slate-400 block font-semibold mb-0.5">Severity:</span>
                <span className="text-red-400 uppercase font-bold">{reportData.incident.severity}</span>
              </div>

              <div>
                <span className="text-slate-400 block font-semibold mb-0.5">Primary Reason:</span>
                <span className="text-red-300">{reportData.incident.reason}</span>
              </div>
            </div>
          </div>

          {/* Root Cause & Evidence */}
          <div className="space-y-3">
            <h3 className="text-xs font-bold uppercase tracking-wider text-orange-400 border-b border-slate-800 pb-2">
              2. Root Cause & Evidence
            </h3>

            <div className="bg-slate-950 p-4 rounded border border-slate-800 space-y-3 text-xs">
              <div className="flex items-center justify-between">
                <span className="text-red-400 font-bold">
                  Step {reportData.root_cause_log?.step_number}: {reportData.root_cause_log?.action}
                </span>
                <span className="text-emerald-400 font-semibold">
                  Confidence: {reportData.incident.confidence}%
                </span>
              </div>

              <p className="text-slate-300 leading-relaxed">
                {reportData.incident.reason}
              </p>

              <div>
                <span className="text-xs font-semibold text-slate-400 block mb-1">
                  Evidence Output Data
                </span>
                <pre className="p-3 rounded bg-slate-900 font-mono text-xs text-red-300 overflow-x-auto whitespace-pre-wrap">
                  {typeof reportData.evidence === 'string'
                    ? reportData.evidence
                    : JSON.stringify(reportData.evidence, null, 2)}
                </pre>
              </div>
            </div>
          </div>

          {/* Solution & Security */}
          <div className="space-y-3">
            <h3 className="text-xs font-bold uppercase tracking-wider text-orange-400 border-b border-slate-800 pb-2">
              3. Solution & Hash Security
            </h3>

            <div className="p-4 rounded bg-orange-500/10 border border-orange-500/20 text-xs text-slate-200 leading-relaxed">
              <span className="font-bold text-orange-400 block mb-1">Recommended Action:</span>
              {reportData.incident.recommendation}
            </div>

            <div className="p-4 rounded bg-slate-950 border border-slate-800 text-xs flex items-center justify-between">
              <div>
                <span className="text-slate-400 font-semibold block">Log Security Verification:</span>
                <span className="text-emerald-400 font-bold">
                  {reportData.hash_integrity?.is_valid ? 'Verified Intact' : 'Tamper Warning'}
                </span>
              </div>
              <span className="text-slate-400">
                {reportData.hash_integrity?.total_steps} Executed Steps Logged
              </span>
            </div>
          </div>
        </div>
      ) : (
        <div className="p-12 text-center text-slate-500">
          <RefreshCw className="w-8 h-8 animate-spin mx-auto mb-2 text-orange-500" />
          <span>Generating report preview...</span>
        </div>
      )}
    </div>
  );
};
